# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Doc vault - Build and deploy Node.js app to Azure Web App - web-8d3ebbb5eba8

on:
  push:
    paths:
      - 'doc-vault(az-storage)/web-app/**'
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: web-8d3ebbb5eba8
  AZURE_WEBAPP_PACKAGE_PATH: 'doc-vault(az-storage)/web-app'
  NODE_VERSION: '18.x'

jobs:
  build:
    defaults:
      run:
        working-directory: doc-vault(az-storage)/web-app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: release.zip
          path: doc-vault(az-storage)/web-app/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: release.zip
      - name: Create target directory
        run: mkdir -p doc-vault\(az-storage\)/web-app
      - name: unzip artifact for deployment
        run: unzip release.zip -d doc-vault\(az-storage\)/web-app/

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.DOC_VAULT_AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
